version: "3.8"
services: 
  # nginx 
  nginx: 
    container_name: 'admin-tool-nginx' 
    image: 'nginx:1.14' 
    ports: 
      - 80:80 
    volumes: 
      - ./src:/srv:rw 
      - ./nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf 
    links: 
      - 'php' 
  # php 
  php: 
    container_name: 'admin-tool-php' 
    build: './php' 
    working_dir: '/srv' 
    command: bash -c 'composer install && php-fpm' 
    volumes: 
      - ./src:/srv 
  # mysql
  db-mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: securerootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./databases/mysql/dump:/dump
      - ./databases/mysql/init.d:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
    networks:
      - recruits
  
  db-postgres:
    build: 
      context: .
      dockerfile: dockerfile.postgres
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    # volumes:
    #   - ./databases/postgres/dump:/dump
    #   - ./databases/postgres/init.d:/docker-entrypoint-initdb.d
    ports: 
      - 5432:5432
    networks:
      - recruits
  
  dbs-admin:
    image: adminer
    container_name: recruits-admin
    restart: always
    ports:
      - 8888:8080
    networks:
      - recruits

networks: 
  recruits:
    name: recruits